# This workflow will build and test golang projects in subdirectories
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.x'

    - name: Build and Test luma-cloud-backend
      run: |
        cd artifacts/luma-cloud-backend
        go build -v ./...
        go test -v ./...

    - name: Build and Test mqtt-service
      run: |
        cd mqtt-service
        go build -v ./...
        go test -v ./...

    - name: Build and Test authentication-service
      run: |
        cd authentication-service
        go build -v ./...
        go test -v ./...
